// Copyright 2026 UTRA-RoboSoccer
// Writes golden_frames.hpp: master-link frames built by the FIRMWARE's own C code.
//
// The C++ codec in humanoid_transport_stm32 is checked against these bytes, so a layout mistake
// in the C++ cannot be hidden by testing the codec against itself.
//
// Regenerate, with soccer-firmware checked out at the commit named in the output's header:
//   g++ -std=c++20 -I <soccer-firmware> generate_golden.cpp -o generate_golden
//   ./generate_golden > golden_frames.hpp
#include <cstdint>
#include <cstdio>
#include <cstring>

#include "firmware/common/include/protocol.h"

namespace
{

void emit_array(const char * name, const std::uint8_t * data, std::size_t len)
{
  std::printf("inline constexpr std::array<std::uint8_t, %zu> %s{{", len, name);
  for (std::size_t i = 0; i < len; ++i) {
    if (i % 12 == 0) {
      std::printf("\n  ");
    }
    std::printf("0x%02X,%s", data[i], (i % 12 == 11 || i + 1 == len) ? "" : " ");
  }
  std::printf("\n}};\n\n");
}

cmd_motor_t make_cmd_motor(
  std::uint8_t mode, std::int16_t pos, std::int16_t vel, std::uint16_t kp, std::uint16_t kd,
  std::int16_t tau, std::uint8_t flags)
{
  cmd_motor_t m;
  std::memset(&m, 0, sizeof(m));
  m.mode_req = mode;
  m.pos = pos;
  m.vel = vel;
  m.kp = kp;
  m.kd = kd;
  m.tau_ff = tau;
  m.flags = flags;
  return m;
}

tele_motor_t make_tele_motor(
  std::int16_t pos, std::int16_t vel, std::int16_t tau, std::uint8_t temp, std::uint8_t state,
  std::uint8_t cause, std::uint8_t mode, std::uint8_t fault, std::uint8_t flags,
  std::uint8_t age, std::uint32_t fault_word, std::uint16_t applied)
{
  tele_motor_t m;
  std::memset(&m, 0, sizeof(m));
  m.pos = pos;
  m.vel = vel;
  m.tau = tau;
  m.temp_c = temp;
  m.state = state;
  m.cause = cause;
  m.motor_mode = mode;
  m.motor_fault = fault;
  m.flags = flags;
  m.fb_age_ms = age;
  m.fault_word = fault_word;
  m.last_applied_seq = applied;
  return m;
}

}  // namespace

int main()
{
  std::printf("// Copyright 2026 UTRA-RoboSoccer\n");
  std::printf("// GENERATED by generate_golden.cpp from the firmware's protocol.h. Do not edit.\n");
  std::printf(
    "// Firmware: soccer-firmware branch akp/single_motor_rework, PROTO_VERSION %u.\n",
    PROTO_VERSION);
  std::printf("#ifndef GOLDEN__GOLDEN_FRAMES_HPP_\n#define GOLDEN__GOLDEN_FRAMES_HPP_\n\n");
  std::printf("#include <array>\n#include <cstdint>\n\n");
  std::printf("namespace humanoid::transport_stm32::golden\n{\n\n");

  // CRC16-CCITT check value: the standard "123456789" vector.
  const std::uint8_t check[] = {'1', '2', '3', '4', '5', '6', '7', '8', '9'};
  std::printf(
    "inline constexpr std::uint16_t kCrcOfCheckString = 0x%04X;\n\n",
    proto_crc16(check, sizeof(check)));

  // Fixed point: x, scale, then the raw value the firmware's encoder produces (round half away
  // from zero, saturating).
  struct FixedPointCase
  {
    float x;
    float scale;
  };
  const FixedPointCase cases[] = {
    {0.5F, PROTO_POS_SCALE}, {-1.25F, PROTO_VEL_SCALE}, {0.00005F, PROTO_POS_SCALE},
    {-0.00005F, PROTO_POS_SCALE}, {3.1416F, PROTO_POS_SCALE}, {4.0F, PROTO_POS_SCALE},
    {-4.0F, PROTO_POS_SCALE}, {327.675F, PROTO_VEL_SCALE}, {0.0F, PROTO_TAU_SCALE},
  };
  std::printf("struct FixedPointCase\n{\n  float x;\n  float scale;\n  std::int16_t raw;\n};\n");
  std::printf(
    "inline constexpr std::array<FixedPointCase, %zu> kFixedPointCases{{\n",
    sizeof(cases) / sizeof(cases[0]));
  for (const auto & c : cases) {
    std::printf(
      "  {%.6ff, %.1ff, %d},\n", static_cast<double>(c.x), static_cast<double>(c.scale),
      proto_f_to_i16(c.x, c.scale, nullptr));
  }
  std::printf("}};\n\n");
  std::printf(
    "inline constexpr std::uint16_t kKpOf15 = %u;\n",
    proto_f_to_u16(15.0F, PROTO_KP_SCALE, nullptr));
  std::printf(
    "inline constexpr std::uint16_t kKdOf1 = %u;\n\n",
    proto_f_to_u16(1.0F, PROTO_KD_SCALE, nullptr));

  // MSG_ROBOT_CMD: header seq 0x1234, ts 0xA1B2C3D4, cycle 0x0102, cmd_seq 0x0304.
  cmd_robot_t cmd;
  std::memset(&cmd, 0, sizeof(cmd));
  cmd.cycle_id = 0x0102U;
  cmd.cmd_seq = 0x0304U;
  cmd.n_chains = 2U;
  cmd.chains[0].chain_id = 0U;
  cmd.chains[0].n_motors = 2U;
  cmd.chains[0].motors[0] = make_cmd_motor(
    REQ_MIT, proto_f_to_i16(0.5F, PROTO_POS_SCALE, nullptr),
    proto_f_to_i16(-1.25F, PROTO_VEL_SCALE, nullptr),
    proto_f_to_u16(15.0F, PROTO_KP_SCALE, nullptr),
    proto_f_to_u16(1.0F, PROTO_KD_SCALE, nullptr),
    proto_f_to_i16(2.5F, PROTO_TAU_SCALE, nullptr), CMD_FLAG_VALID);
  cmd.chains[0].motors[1] =
    make_cmd_motor(REQ_HOLD, 0, 0, 0, 0, 0, CMD_FLAG_VALID | CMD_FLAG_FAULT_RESET);
  cmd.chains[1].chain_id = 1U;
  cmd.chains[1].n_motors = 1U;
  cmd.chains[1].motors[0] = make_cmd_motor(
    REQ_DAMPED, 0, 0, 0, proto_f_to_u16(2.0F, PROTO_KD_SCALE, nullptr), 0,
    CMD_FLAG_VALID | CMD_FLAG_USE_CONFIG_GAINS);
  std::uint8_t cmd_frame[MSG_HEADER_SIZE + sizeof(cmd_robot_t)];
  std::uint16_t n = proto_build(
    cmd_frame, sizeof(cmd_frame), MSG_ROBOT_CMD, 0x1234U, NODE_JETSON, NODE_MASTER, 0xA1B2C3D4U,
    reinterpret_cast<const std::uint8_t *>(&cmd), sizeof(cmd));
  emit_array("kRobotCmdFrame", cmd_frame, n);

  // MSG_ROBOT_TELE, populated prefix only (header + n_chains), as the master transmits it.
  tele_robot_t tele;
  std::memset(&tele, 0, sizeof(tele));
  tele.cycle_id = 0xFFFEU;
  tele.master_time_us = 0xDEADBEEFU;
  tele.last_cmd_seq_rx = 0x1111U;
  tele.cmd_seq_active = 0x2222U;
  tele.cmd_on_time = 5U;
  tele.cmd_late = 6U;
  tele.cmd_missing = 7U;
  tele.cmd_duplicate = 8U;
  tele.n_chains = 2U;
  tele.robot_state = ROBOT_READY;
  tele.chains[0].chain_id = 0U;
  tele.chains[0].n_motors = 2U;
  tele.chains[0].spi_seq_echo = 7U;
  tele.chains[0].spi_resyncs = 1U;
  tele.chains[0].slave_time_us = 123456789U;
  tele.chains[0].cmd_crc_errors = 2U;
  tele.chains[0].can_tx_errors = 3U;
  tele.chains[0].spi_tx_arm_fails = 4U;
  tele.chains[0].motors[0] = make_tele_motor(
    12345, -250, 1234, 41, LIFE_MIT, CAUSE_NONE, 2U, 0x04U,
    TELE_FLAG_CLAMPED_POS | TELE_FLAG_CMD_STALE, 3U, 0x3022U, 0xBEEFU);
  tele.chains[0].motors[1] = make_tele_motor(
    -31416, 32767, -32768, 255, LIFE_HOLD, CAUSE_WATCHDOG, 1U, 0x3FU, 0xFFU, 255U, 0xFFFFFFFFU,
    0U);
  tele.chains[1].chain_id = 1U;
  tele.chains[1].n_motors = 1U;
  tele.chains[1].motors[0] = make_tele_motor(
    1, -1, 0, 20, LIFE_FAULT, CAUSE_OVERTORQUE, 0U, 0U, 0U, 0U, 0U, 1U);
  const auto prefix = static_cast<std::uint16_t>(20U + 2U * sizeof(tele_chain_t));
  std::uint8_t tele_frame[MSG_HEADER_SIZE + sizeof(tele_robot_t)];
  n = proto_build(
    tele_frame, sizeof(tele_frame), MSG_ROBOT_TELE, 0x0007U, NODE_MASTER, NODE_JETSON,
    0x01020304U, reinterpret_cast<const std::uint8_t *>(&tele), prefix);
  emit_array("kRobotTeleFrame", tele_frame, n);

  // MSG_MASTER_STATUS
  MasterStatus status;
  std::memset(&status, 0, sizeof(status));
  status.robot_state = ROBOT_READY;
  status.slave_alive = 0x03U;
  status.uptime_ms = 123456U;
  status.link_errors = 9U;
  status.rx_frames = 1000U;
  status.master_poll_hz = 200U;
  status.telemetry_hz = 200U;
  status.slave_tick_hz = 200U;
  status.host_cmd_hz = 50U;
  std::uint8_t status_frame[MSG_HEADER_SIZE + sizeof(MasterStatus)];
  n = proto_build(
    status_frame, sizeof(status_frame), MSG_MASTER_STATUS, 0x0042U, NODE_MASTER, NODE_JETSON,
    5000U, reinterpret_cast<const std::uint8_t *>(&status), sizeof(status));
  emit_array("kMasterStatusFrame", status_frame, n);

  std::printf("}  // namespace humanoid::transport_stm32::golden\n\n");
  std::printf("#endif  // GOLDEN__GOLDEN_FRAMES_HPP_\n");
  return 0;
}
